export enum QueryKeys {
  CART = "CART",
  PRODUCTS = "PRODUCTS",
  PRODUCT = "PRODUCT",
  MENU_LOCATIONS = "MENU_LOCATIONS",
  MENU_LOCATION = "MENU_LOCATION",
  MENU_ITEMS = "MENU_ITEMS",
  MENU_ITEM = "MENU_ITEM",
  STREAMS = "STREAMS",
  STREAM = "STREAM"
}
